$(document).ready(function(){
            $(".checkB").hide();
            $(".short").hide();
            $(".long").hide();
            $("#password").keypress(function(){
                var $password=$("#password");
                var jsonObj={
                    password:$password.val()
                };
                $.get("ajaxRequest/getPwdCheck.jsp",jsonObj,function(data,textStatus){
                	if(data==-1){
                		$(".short").show();
                		$(".long").hide();
                		$(".weak").css("background","");
                        $(".middle").css("background","");
                        $(".strong").css("background","");
                	}
                    if(data==0){
                       $(".weak").css("background","#f37f41");
                       $(".middle").css("background","");
                       $(".strong").css("background","");
                       $(".short").hide();
                       $(".long").hide();
                    }
                    if(data==1){
                    	$(".weak").css("background","#f37f41");
                    	$(".middle").css("background","gray");
                    	$(".strong").css("background","");
                    	$(".short").hide();
                        $(".long").hide();
                    }
                    if(data==2){
                    	$(".weak").css("background","#f37f41");
                    	$(".middle").css("background","gray");
                    	$(".strong").css("background","#4ec230");
                    	$(".short").hide();
                        $(".long").hide();
                    }
                    if(data==3){
                    	$(".short").hide();
                		$(".long").show();
                		$(".weak").css("background","");
                    	$(".middle").css("background","");
                    	$(".strong").css("background","");
                    }
                });
            });
        });